---
title: "urap"
author: "Jay Zhang"
date: "4/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(MASS)
hh <- read.csv("./Csv/hhpub.csv")
veh <- read.csv("./Csv/vehpub.csv")

AVGINCOME = hh$HHFAMINC
AVGINCOME[hh$HHFAMINC == '1'] = 10000
AVGINCOME[hh$HHFAMINC == '2'] = (10000+14999)/2
AVGINCOME[hh$HHFAMINC == '3'] = (15000+24999)/2
AVGINCOME[hh$HHFAMINC == '4'] = (25000+34999)/2
AVGINCOME[hh$HHFAMINC == '5'] = (35000+49999)/2
AVGINCOME[hh$HHFAMINC == '6'] = (50000+74999)/2
AVGINCOME[hh$HHFAMINC == '7'] = (75000+99999)/2
AVGINCOME[hh$HHFAMINC == '8'] = (100000+124999)/2
AVGINCOME[hh$HHFAMINC == '9'] = (125000+149999)/2
AVGINCOME[hh$HHFAMINC == '10'] = (150000+199999)/2#
AVGINCOME[hh$HHFAMINC == '11'] = 200000
AVGINCOME[hh$HHFAMINC < 0] = NA
hh$HHFAMINC = AVGINCOME


```

```{r}
bestmile = data.frame("HOUSEID" = veh$HOUSEID, "BESTMILE" = veh$BESTMILE)
bestmile = aggregate(bestmile$BESTMILE, by=list(bestmile$HOUSEID), FUN=sum)
names(bestmile) = c("HOUSEID", "BESTMILE")
nhts = data.frame(merge(hh, bestmile, by = "HOUSEID"))

#create column for white
nhts$WHITE <- rep(0,nrow(nhts))
nhts$WHITE[nhts$HH_RACE==1]=1
```

```{r}
head(nhts)
str(nhts)
state <- dummy.data.frame(data.frame(nhts$HHSTATE))
colnames(state) <- c("AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY")

dat = data.frame(nhts$DRVRCNT, nhts$CNTTDHH, nhts$HHFAMINC, nhts$HHSIZE, nhts$HHVEHCNT, nhts$WHITE, nhts$BESTMILE,state)
names(dat)[1:7]=c("DRVRCNT", "CNTTDHH", "HHFAMINC", "HHSIZE", "HHVEHCNT", "WHITE", "BESTMILE")

dat = na.omit(dat)
state.null = lm(BESTMILE ~ 1, data = dat)
state.full = lm(BESTMILE ~ ., data=dat)

summary(state.full)



```

